[package]
name = "customengine"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = { version = "0.38.0", features=["linked"] }
ash-window = "0.13.0"
winit = { version = "0.29", features = ["rwh_06"] }
